### ISSUE TITLE
ISP LH2 Engine

### ISSUE THREAD

**Issue by AstroWell** [AstroWell/Knes#4]
ISP need to ne reduced for LH2 Engine HM7 and HM60.... see Vulcain  342 and 220sl

or Beale settings :  315 and 295sl

**Comment by zorg2044** [comment]
Hi Well, I would personally recommend going with Vulcain like stats. Beale set up his RD0120 more like a sea level lifter engine rather than a sustainer probably due to the huge mass of the 5m fuel tank.

Since these are upper stage engines, the Vulcain like stats would work well and should make them useful as high efficiency upper stage or sustainer LFO engines.

Or if you want to make it a pure upper-stage and not have it be useful as a sustainer you could go with 350 and 90 like the squad Poodle?

**Comment by AstroWell** [comment]
Go for 342 Vac 220 SL, and i made test to see what that look like.
With 38Kn of Thrust for HM7 that already only a Vacuum engine, i don't think i need to reduce more like the poodle
